### ISSUE TITLE
Output file must end with ".svg", ".png" or ".pdf"

### ISSUE THREAD

**Issue by DoDoENT** [mermaid-js/mermaid-cli#274]
**Describe the bug**
I installed the mmdc v8.11.0 from homebrew using `brew install mermaid-cli` as described in documentation and run `mmdc -i documentation.template.md -o documentation.md` where `documentation.template.md` contains mermaid snippets in markdown file. Then, instead of getting transformed MD, I got the error `Output file must end with ".svg", ".png" or ".pdf"`.

**To Reproduce**

1. Install latest mermaid-cli from Homebrew with `brew install mermaid-cli`
2. Create a markdown file with mermaid blocks
3. execute `mmdc -i yourfile.md -o destination.md`
4. See the error

**Expected behavior**
Instead of error, a transformed markdown file should appear.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS
- Browser: N/A
- Version: 8.11.0

**Comment by metapost** [comment]
I got the same error.
macos
mmdc version: 8.11.0

**Comment by zats** [comment]
Looks like it's been fixed in the master, but the version hasn't been released yet.
FYIF, I followed the instructions from `CONTRIBUTING.md` and `building.md` to run latest version locally. 
Effectively after checking out code, you'll need to:

```bash
yarn install; source copy_modules.sh
node index.bundle.js -i mydoc.template.md -o mydoc.out.md
```

**Comment by MindaugasLaganeckas** [comment]
We are on release 9.0.3. Please, check if the error is fixed there.

**Comment by zats** [comment]
@MindaugasLaganeckas  do you think it's possible that brew version hasn't been bumped? I just tried updating and it suggests that 8.11.0 is the newest version available

**Comment by MindaugasLaganeckas** [comment]
We have this issue https://github.com/mermaid-js/mermaid-cli/issues/288

**Comment by DoDoENT** [comment]
But even if I install from NPM with `npm install -g mermaid`, I still don't get the version 9.0.3.

The version from npm, strangely, reports `0.2.4`. What did I do wrong?

**Comment by zats** [comment]
> EDIT: OK, I needed to run `npm install -g @mermaid-js/mermaid-cli`. 😊 Then it works correctly.

This is a great workaround, thanks!
